version: '3'

services:
  project:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_USER: "post"
      DB_PASSWORD: "son1540"
      DB_NAME: "lab3DB"
      DB_HOST: "db:5432"
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "post"
      POSTGRES_PASSWORD: "son1540"
      POSTGRES_DB: "lab3DB"
    ports:
      - "5432:5432"
