"""Functionality by variant #3

Revision ID: 66bea8ab7759
Revises: c434d7de6335
Create Date: 2024-01-03 22:58:06.526944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bea8ab7759'
down_revision = 'c434d7de6335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
