"""Functionality by variant #2

Revision ID: c434d7de6335
Revises: 1b45e67dfaa6
Create Date: 2024-01-03 22:03:43.425077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c434d7de6335'
down_revision = '1b45e67dfaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_general')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_general', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
